const auth = require('./auth')
const users = require('./users')
const classroom = require('./class')
const courses = require('./course')
const enroll = require('./enroll')
const category = require('./category')
const lesson = require('./lesson')
const quizz = require('./quizz')
const service = require('./service')
const payment = require('./payment')
const post = require('./post')
const message = require('./message')
const routers = (app) => {  
  app.use('/auth', auth)
  app.use('/users', users)
  app.use('/classrooms', classroom)
  app.use('/course', courses)
  app.use('/enroll', enroll)
  app.use('/category', category)
  app.use('/lesson',lesson)
  app.use('/quizzes',quizz)
  app.use('/services',service)
  app.use('/payment',payment)
  app.use('/post', post)
  app.use('/message', message)
}
module.exports = routers;